name: Generate infrastructure for the environment
on: [push]
jobs:
  Build-Kubernetes-Environment:
    runs-on: ubuntu-latest
    env:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    steps:
      - name: Pull down code base
        uses: actions/checkout@v2
      - run: sudo bash ${{ github.workspace }}/init.sh
      - run: terraform -chdir=${{ github.workspace }}/kops init
      - run: terraform -chdir=${{ github.workspace }}/kops apply -input=false -auto-approve
      - run: echo "Job Status - ${{ job.status }}."
